spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: dev
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/colini
      username: friday
      password: pass
    jpa:
      hibernate:
        ddl-auto: validate
