spring:
  profiles:
    active: dev

datasource:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_seq: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security.oauth2.jwt: DEBUG

# security
my-app:
  client-id: myApp
  client-secret: pass
  admin-id: admin@email.com
  admin-password: admin
  user-id: user@email.com
  user-password: user

security:
  oauth2:
    client:
      registration:
        google:
          clientId: 434541373271-h977ssvpjlv003tdkfof6f49pqg8fsqr.apps.googleusercontent.com
          clientSecret: d9k1lSwtPwrfHBtpwrp-fTac
          scope: email, profile
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
