spring:
  profiles:
    active: dev

datasource:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

# security
my-app:
  client-id: myApp
  client-secret: pass
  admin-id: admin@email.com
  admin-password: admin
  user-id: user@email.com
  user-password: user
