spring:
  datasource:
    url: jdbc:mysql://localhost:3306/colini
    username: friday
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

