datasource:
  url: jdbc:mysql://localhost:3306/colini
  username: friday
  password: pass
jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

