spring:
  profiles:
    active: dev

datasource:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# security
my-app:
  client-id: myApp
  client-secret: pass
  admin-id: admin@email.com
  admin-password: admin
  user-id: user@email.com
  user-password: user

---
spring:
  profiles: local

datasource:
  platform: h2
  url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
  username: sa
  password:
  driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/colini
    username: friday
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

